server_connect_timeout: 5000
enforce_secure_profile: false
remote_ping_cache: -1
forge_support: false
player_limit: -1
permissions:
  default:
  - bungeecord.command.server
  - bungeecord.command.list
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
  - bungeecord.command.kick
  - bungeecord.command.send
  - bungeecord.command.find
timeout: 30000
log_commands: false
network_compression_threshold: 256
online_mode: false
servers:
  lobby:
    motd: '&1Just another BungeeCord - Forced Host'
    address: roshan.falixsrv.me:58761
    restricted: false
listeners:
- query_port: 25577
  motd: '&1Another Bungee server'
  tab_list: GLOBAL_PING
  query_enabled: false
  proxy_protocol: false
  forced_hosts:
    pvp.md-5.net: pvp
  ping_passthrough: false
  priorities:
  - lobby
  bind_local_address: true
  host: 0.0.0.0:25577
  max_players: 1
  tab_size: 60
  force_default_server: true
prevent_proxy_connections: false
ip_forward: false
remote_ping_timeout: 5000
reject_transfers: false
disabled_commands:
- disabledcommandhere
connection_throttle: 4000
stats: ce82e89e-0095-4c7f-95f6-d055195e3561
connection_throttle_limit: 3
groups:
  md_5:
  - admin
log_pings: true
